const collectionData = [
  { name: 'Trending in Jakarta', link: '/restaurants/jakarta' },
  { name: 'Menu Sarapan', link: '/cuisine/breakfast' },
  { name: 'Makanan Indonesia', link: '/cuisine/indonesia' },
  { name: 'Makanan Sehat', link: '/cuisine/healthy' },
];

const restaurantData = [
  {
    id: 1,
    name: 'JPW Cafe & Resto',
    rating: '4.6',
    avg_price: 35,
    distance: '3.2km',
    location: 'Sukmajaya, Depok',
    tags: ['Kopi', 'Indonesia'],
    type: 'Fine Dining',
  },
  {
    id: 2,
    name: 'Goobne',
    rating: '4.4',
    avg_price: 12,
    distance: '4.8km',
    location: 'Pantai Indah Kapuk, Jakarta',
    tags: ['Korea', 'Makanan Sehat'],
    type: 'Burger',
  },
  {
    id: 3,
    name: 'Golden Lamian',
    rating: '4.2',
    avg_price: 15,
    distance: '5.2km',
    location: 'Senayan City, Senayan, Jakarta',
    tags: ['Bakmi', 'Chinese', 'Cepat Saji'],
    type: 'Fine Dining',
  },
  {
    id: 4,
    name: 'Afterhour',
    rating: '3.7',
    avg_price: 8,
    distance: '3.2km',
    location: 'Sarinah Building, Thamrin, Jakarta',
    tags: ['GrillHouse', 'Itali'],
    type: 'Burger',
  },
  {
    id: 5,
    name: 'Ecology Bistro & Lounge',
    rating: '4.1',
    avg_price: 21,
    distance: '4.8km',
    location: 'Pantai Indah Kapuk, Jakarta',
    tags: ['western'],
    type: 'Fine Dining',
  },
  {
    id: 6,
    name: "Melly's Garden",
    rating: '4.0',
    avg_price: 30,
    distance: '1.8km',
    location: 'Menteng, Jakarta',
    tags: ['Jawa', 'Indonesia', 'Western'],
    type: 'Fine Dining',
  },
  {
    id: 7,
    name: 'Sushi Express',
    rating: '4.5',
    avg_price: 25,
    distance: '2.5km',
    location: 'Gandaria City, Kebayoran Lama, Jakarta',
    tags: ['Sushi', 'Japanese'],
    type: 'Sushi',
  },
  {
    id: 8,
    name: 'Pizza Haven',
    rating: '4.3',
    avg_price: 18,
    distance: '6.5km',
    location: 'Kemang, Jakarta Selatan',
    tags: ['Pizza', 'Italian'],
    type: 'Pizza',
  },
  {
    id: 9,
    name: 'Sushi Palace',
    rating: '4.7',
    avg_price: 30,
    distance: '2.0km',
    location: 'Plaza Senayan, Jakarta',
    tags: ['Sushi', 'Japanese'],
    type: 'Sushi',
  },
  {
    id: 10,
    name: 'Tokyo Sushi Bar',
    rating: '4.5',
    avg_price: 25,
    distance: '3.5km',
    location: 'Pacific Place, Jakarta',
    tags: ['Sushi', 'Japanese'],
    type: 'Sushi',
  },
  {
    id: 11,
    name: 'Sakura Sushi House',
    rating: '4.8',
    avg_price: 35,
    distance: '1.8km',
    location: 'Kemang, Jakarta Selatan',
    tags: ['Sushi', 'Japanese'],
    type: 'Sushi',
  },
  {
    id: 12,
    name: 'Burger Tek',
    rating: '4.8',
    avg_price: 10,
    distance: '1.0km',
    location: 'Depok Town Square',
    tags: ['Street Food', 'Indonesia'],
    type: 'Burger',
  },
  {
    id: 13,
    name: 'Healthy Bowls',
    rating: '4.6',
    avg_price: 20,
    distance: '3.5km',
    location: 'Kuningan City, Jakarta',
    tags: ['Salad', 'Healthy'],
    type: 'Fine Dining',
  },
  {
    id: 14,
    name: 'Ramen Delight',
    rating: '4.2',
    avg_price: 22,
    distance: '4.0km',
    location: 'Plaza Indonesia, Jakarta',
    tags: ['Ramen', 'Japanese'],
    type: 'Fine Dining',
  },
  {
    id: 15,
    name: 'Veggie Delight',
    rating: '4.7',
    avg_price: 15,
    distance: '2.0km',
    location: 'Cilandak Town Square, Depok',
    tags: ['Vegetarian', 'Healthy'],
    type: 'Fine Dining',
  },
];

export { restaurantData, collectionData };
